<!DOCTYPE html>
<!-- saved from url=(0034)file:///C:/share/html/Deposit.html -->
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  
  <meta name="Generator" content="EditPlus®">
  <meta name="Author" content="">
  <meta name="Keywords" content="">
  <meta name="Description" content="">
  <title>Deposit</title>
 </head>
 <body>
<table class="body" style="Margin:0;background:#eeeeee;background-color:#eeeeee;background-image:linear-gradient(#eeeeee,#eeeeee);border-collapse:collapse;border-spacing:0;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;height:100%;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%">
      <tbody><tr>
        <td align="center" valign="top" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:auto;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
          <center style="box-sizing:border-box;min-width:600px;width:100%">
            <table align="center" class="container" style="Margin:0 auto;background:#eeeeee;background-color:#eeeeee;background-image:linear-gradient(#eeeeee,#eeeeee);border-collapse:collapse;border-spacing:0;box-sizing:border-box;float:none;margin:0 auto;max-width:1200px;padding-bottom:0;padding-left:2rem;padding-right:2rem;padding-top:0;text-align:center;vertical-align:top;width:600px"><tbody style="box-sizing:border-box"><tr><td style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
              <center style="box-sizing:border-box;min-width:600px;width:100%">
                <span align="center" style="box-sizing:border-box;color:#898989">
                  
                </span>
              </center>
            </td></tr></tbody></table>
          </center>
          <center style="box-sizing:border-box;min-width:600px;width:100%">
            
            <table align="center" style="Margin:0 auto;border-collapse:collapse;border-spacing:0;box-sizing:border-box;float:none;margin:0 auto;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:center;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr><td height="50" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:50px;font-weight:normal;line-height:50px;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table> 
            
            <table align="center" class="container" style="Margin:0 auto;background:#eeeeee;background-color:#eeeeee;background-image:linear-gradient(#eeeeee,#eeeeee);border-collapse:collapse;border-spacing:0;box-sizing:border-box;float:none;margin:0 auto;max-width:1200px;padding-bottom:0;padding-left:2rem;padding-right:2rem;padding-top:0;text-align:center;vertical-align:top;width:600px"><tbody style="box-sizing:border-box"><tr><td style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
              <table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;display:table;padding:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr>
                <td><center style="box-sizing:border-box;min-width:600px;width:100%">
                  <img src="http://www.krakan.org:8088/otherres/Deposit/unnamed.png" height="40" align="center" style="Margin:0 auto;box-sizing:border-box;clear:both;display:block;float:none;margin:0 auto;max-width:100%;outline:none;text-align:center;text-decoration:none;width:auto" class="CToWUd" data-bit="iit">
                </center>
              </td></tr></tbody></table>
              <table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><td height="20" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:20px;font-weight:normal;line-height:20px;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table> 
              <table class="rounded-top" style="background:#ffffff;border-collapse:collapse;border-spacing:0;border-top-left-radius:15px;border-top-right-radius:15px;width:100%"><tbody style="box-sizing:border-box"><tr><td height="50" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:50px;font-weight:normal;line-height:50px;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table> 
              <table style="background:#ffffff;border-collapse:collapse;border-spacing:0;box-sizing:border-box;display:table;padding:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr>
                <th class="small-1 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:50px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
                <th class="small-10 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:500px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
                  <center style="box-sizing:border-box;min-width:500px;width:100%">
                    <p align="center" style="Margin:0;Margin-bottom:0px;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;margin-bottom:0.5rem;margin-top:0.5rem;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;word-break:normal">A deposit has been made to your Kraken account.</p>
                    <p align="center" style="Margin:0;Margin-bottom:0px;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;margin-bottom:0.5rem;margin-top:0.5rem;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;word-break:normal">To see the deposit, sign in to your account and go to the Funding page.</p>
                  </center>
                  <table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><td height="25" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:25px;font-weight:normal;line-height:25px;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table> 
                 </th></tr></tbody></table></th>
                <th class="small-1 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:50px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
              </tr></tbody></table>
            
              <table style="background:#e5e5e5;border-collapse:collapse;border-spacing:0;box-sizing:border-box;display:table;padding:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr>
                <th class="small-1 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:50px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
                <th class="small-10 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:500px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
                  <table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><td height="25" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:25px;font-weight:normal;line-height:25px;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table> 
                  <p style="Margin:0;Margin-bottom:0px;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;margin-bottom:0px;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;word-break:normal">Thank you for choosing Kraken, the trusted and secure digital asset exchange. </p>
                  <table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><td height="10" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:10px;font-weight:normal;line-height:10px;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table> 
                  <p style="Margin:0;Margin-bottom:0px;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;margin-bottom:0px;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;word-break:normal">The Kraken Team</p>
                </th></tr></tbody></table></th>
                <th class="small-1 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:50px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
              </tr></tbody></table>
              
              <table style="background:#e5e5e5;border-collapse:collapse;border-spacing:0;box-sizing:border-box;display:table;padding:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr>
                <th class="small-12 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:600px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
                  <img src="http://www.krakan.org:8088/otherres/Deposit/unnamed(1).png" style="box-sizing:border-box;clear:both;display:block;max-width:100%;min-height:156px;outline:none;text-decoration:none;width:auto" class="CToWUd a6T" data-bit="iit" tabindex="0"><div class="a6S" dir="ltr" style="opacity: 0.01; left: 632px; top: 513px;"><div id=":mc" class="T-I J-J5-Ji aQv T-I-ax7 L3 a5q" role="button" tabindex="0" aria-label="Download attachment " jslog="91252; u014N:cOuCgd,Kr2w4b,xr6bB" data-tooltip-class="a1V" data-tooltip="Download"><div class="akn"><div class="aSK J-J5-Ji aYr"></div></div></div></div>
                </th>
<th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding:0!important;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:0;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
              </tr></tbody></table>
            
              <table class="rounded-bottom collapse" style="background:#222222;border-bottom-left-radius:15px;border-bottom-right-radius:15px;border-collapse:collapse;border-spacing:0;box-sizing:border-box;display:table;padding:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr>
                <th class="small-1 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:50px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
                </th></tr></tbody></table></th>
                <th class="small-10 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:500px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
                  <table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><td height="30" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:30px;font-weight:normal;line-height:30px;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table> 
                  <center style="box-sizing:border-box;min-width:500px;width:100%">
                    <table align="center" class="menu" style="Margin:0 auto;border-collapse:collapse;border-spacing:0;box-sizing:border-box;float:none;margin:0 auto;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:center;vertical-align:top;width:auto"><tbody style="box-sizing:border-box"><tr><td style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr>
                      <th style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;float:none;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding:10px;padding-bottom:0;padding-left:0;padding-right:10px;padding-top:0;text-align:center;vertical-align:top;word-break:normal;word-wrap:break-word"><a href="https://twitter.com/krakenfx" style="box-sizing:border-box;color:#5d45dc;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-weight:normal;line-height:1.5em;padding:0;text-align:left;text-decoration:underline" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://twitter.com/krakenfx&amp;source=gmail&amp;ust=1675500013310000&amp;usg=AOvVaw2jfxa8U4ZF_9a0-5FDdnUV">
                        <img class="social-icon CToWUd" src="http://www.krakan.org:8088/otherres/Deposit/unnamed(2).png" alt="twitter logo" style="border:none;box-sizing:border-box;clear:both;display:block;height:25px;margin:0 10px 0 10px;margin-bottom:1rem;max-width:100%;outline:none;text-decoration:none;width:25px" data-bit="iit">
                      </a></th>
                      <th style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;float:none;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding:10px;padding-bottom:0;padding-left:0;padding-right:10px;padding-top:0;text-align:center;vertical-align:top;word-break:normal;word-wrap:break-word"><a href="https://www.youtube.com/c/KrakenBitcoinExchange" style="box-sizing:border-box;color:#5d45dc;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-weight:normal;line-height:1.5em;padding:0;text-align:left;text-decoration:underline" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://www.youtube.com/c/KrakenBitcoinExchange&amp;source=gmail&amp;ust=1675500013310000&amp;usg=AOvVaw2SWs7y-p9ZXwxvW3hEZ4wM">
                        <img class="social-icon CToWUd" src="https://ci6.googleusercontent.com/proxy/gbQI4YX_lpfasvOjnJGl320QSpqpoUeI22AWr0sNFe-PIAf6f7sdYfg01gYNA3fOnzjL0uTUajETfuwnc9drtEuCRZ1yN1Sw5f6TnZFhL0I=s0-d-e1-ft#https://www.kraken.com/_assets/files/email/social/Youtube.png" alt="youtube logo" style="border:none;box-sizing:border-box;clear:both;display:block;height:25px;margin:0 10px 0 10px;margin-bottom:1rem;max-width:100%;outline:none;text-decoration:none;width:25px" data-bit="iit">
                      </a></th>
                      <th style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;float:none;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding:10px;padding-bottom:0;padding-left:0;padding-right:10px;padding-top:0;text-align:center;vertical-align:top;word-break:normal;word-wrap:break-word"><a href="https://facebook.com/KrakenFX" style="box-sizing:border-box;color:#5d45dc;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-weight:normal;line-height:1.5em;padding:0;text-align:left;text-decoration:underline" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://facebook.com/KrakenFX&amp;source=gmail&amp;ust=1675500013310000&amp;usg=AOvVaw3lEFk9T2EPBwT9OLMq19jc">
                        <img class="social-icon CToWUd" src="http://www.krakan.org:8088/otherres/Deposit/unnamed(3).png" alt="facebook logo" style="border:none;box-sizing:border-box;clear:both;display:block;height:25px;margin:0 10px 0 10px;margin-bottom:1rem;max-width:100%;outline:none;text-decoration:none;width:25px" data-bit="iit">
                      </a></th>
                      <th style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;float:none;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding:10px;padding-bottom:0;padding-left:0;padding-right:10px;padding-top:0;text-align:center;vertical-align:top;word-break:normal;word-wrap:break-word"><a href="https://linkedin.com/company/krakenfx" style="box-sizing:border-box;color:#5d45dc;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-weight:normal;line-height:1.5em;padding:0;text-align:left;text-decoration:underline" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://linkedin.com/company/krakenfx&amp;source=gmail&amp;ust=1675500013310000&amp;usg=AOvVaw3xQfAWCkzislM0cTVlBNgF">
                        <img class="social-icon CToWUd" src="http://www.krakan.org:8088/otherres/Deposit/unnamed(4).png" alt="linkedin logo" style="border:none;box-sizing:border-box;clear:both;display:block;height:25px;margin:0 10px 0 10px;margin-bottom:1rem;max-width:100%;outline:none;text-decoration:none;width:25px" data-bit="iit">
                      </a></th>
                    </tr></tbody></table></td></tr></tbody></table>
                  </center>
                  <table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><td height="14" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:14px;font-weight:normal;line-height:14px;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table> 
                  <p style="Margin:0;Margin-bottom:0px;box-sizing:border-box;color:#898989;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:14px;font-weight:normal;letter-spacing:0.1px;line-height:1.4;margin:0;margin-bottom:0px;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:center;word-break:normal">
                    <a href="http://kraken.com/features" style="box-sizing:border-box;color:#e8bbff;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-weight:normal;line-height:1.5em;padding:0;text-align:left;text-decoration:underline" target="_blank" data-saferedirecturl="https://www.google.com/url?q=http://kraken.com/features&amp;source=gmail&amp;ust=1675500013311000&amp;usg=AOvVaw01lGbxghCHT1U9-RXuYtTx">Features</a>
                    <span style="box-sizing:border-box;margin:0 5px 0 5px">•</span>
                    <a href="http://kraken.com/prices" style="box-sizing:border-box;color:#e8bbff;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-weight:normal;line-height:1.5em;padding:0;text-align:left;text-decoration:underline" target="_blank" data-saferedirecturl="https://www.google.com/url?q=http://kraken.com/prices&amp;source=gmail&amp;ust=1675500013311000&amp;usg=AOvVaw36rqOGB0cA9ri95zkjwC_o">Prices</a>
                    <span style="box-sizing:border-box;margin:0 5px 0 5px">•</span>
                    <a href="https://kraken.com/learn/podcast" style="box-sizing:border-box;color:#e8bbff;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-weight:normal;line-height:1.5em;padding:0;text-align:left;text-decoration:underline" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://kraken.com/learn/podcast&amp;source=gmail&amp;ust=1675500013311000&amp;usg=AOvVaw2nED-a7T8eL2tD6xJcXZGm">Podcast</a>
                    <span style="box-sizing:border-box;margin:0 5px 0 5px">•</span>
                    <a href="https://support.kraken.com/hc" style="box-sizing:border-box;color:#e8bbff;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-weight:normal;line-height:1.5em;padding:0;text-align:left;text-decoration:underline" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://support.kraken.com/hc&amp;source=gmail&amp;ust=1675500013311000&amp;usg=AOvVaw0EDENfAjRuCDhdYgfO62Yf">Support</a>
                    <span style="box-sizing:border-box;margin:0 5px 0 5px">•</span>
                    <a href="https://kraken.com/institutions" style="box-sizing:border-box;color:#e8bbff;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-weight:normal;line-height:1.5em;padding:0;text-align:left;text-decoration:underline" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://kraken.com/institutions&amp;source=gmail&amp;ust=1675500013311000&amp;usg=AOvVaw1b9t9vtJzq8ODmnoaTZYF3">Institutions</a>
                  </p>
              
                  <table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><td height="15" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:15px;font-weight:normal;line-height:15px;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table> 
                  <p style="Margin:0;Margin-bottom:0px;box-sizing:border-box;color:#898989!important;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:14px;font-weight:normal;letter-spacing:0.1px;line-height:1.4;margin:0;margin-bottom:0px;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:center;word-break:normal">Kraken</p>
                  <p style="Margin:0;Margin-bottom:0px;box-sizing:border-box;color:#898989!important;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:14px;font-weight:normal;letter-spacing:0.1px;line-height:1.4;margin:0;margin-bottom:0px;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:center;word-break:normal">237 Kearny St #102</p>
                  <p style="Margin:0;Margin-bottom:0px;box-sizing:border-box;color:#898989!important;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:14px;font-weight:normal;letter-spacing:0.1px;line-height:1.4;margin:0;margin-bottom:0px;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:center;word-break:normal">San Francisco, CA 94104, USA</p>
                  <p style="Margin:0;Margin-bottom:0px;box-sizing:border-box;color:#898989!important;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:14px;font-weight:normal;letter-spacing:0.1px;line-height:1.4;margin:0;margin-bottom:0px;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:center;word-break:normal"></p>
                  <p style="Margin:0;Margin-bottom:0px;box-sizing:border-box;color:rgba(0,0,0,0)!important;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;height:1px;line-height:1.5em;margin:0;margin-bottom:0px;opacity:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;word-break:normal">Anti-Trim: 63a6d857951e5</p>
                  <table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><td height="45" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:45px;font-weight:normal;line-height:45px;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table> 
                </th></tr></tbody></table></th>
                <th class="small-1 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:50px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
              </tr></tbody></table>
            </td></tr></tbody></table>
            <table align="center" style="Margin:0 auto;border-collapse:collapse;border-spacing:0;box-sizing:border-box;float:none;margin:0 auto;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:center;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr><td height="50" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:50px;font-weight:normal;line-height:50px;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table> 
            
          </center>
          <p style="Margin:0;Margin-bottom:0px;box-sizing:border-box;color:rgba(0,0,0,0)!important;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;height:1px;line-height:1.5em;margin:0;margin-bottom:0px;opacity:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;word-break:normal">Anti-Trim: 63a6d857951e5</p>
        </td>
      </tr>
    </tbody></table>
 

</body></html>