<!DOCTYPE html>
<!-- saved from url=(0033)file:///C:/share/html/Verify.html -->
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  
  <meta name="Generator" content="EditPlus®">
  <meta name="Author" content="">
  <meta name="Keywords" content="">
  <meta name="Description" content="">
  <title>Verify</title>
 </head>
 <body>
  

            <table class="show-for-large" style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><td height="20" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:20px;font-weight:normal;line-height:20px;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table> 

            <table class="rounded-top" style="background:#ffffff;border-collapse:collapse;border-spacing:0;border-top-left-radius:15px;border-top-right-radius:15px;width:100%"><tbody style="box-sizing:border-box"><tr><td height="30" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:30px;font-weight:normal;line-height:30px;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table> 
            
            <table style="background:#ffffff;border-collapse:collapse;border-spacing:0;box-sizing:border-box;display:table;padding:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr>
              <th class="small-1 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:50px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
              <th class="small-5 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:200px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
                 <img src="./Verify/unnamed.png" width="113" height="18" style="box-sizing:border-box;clear:both;display:block;max-width:100%;outline:none;text-decoration:none;width:auto" class="CToWUd" data-bit="iit"> 
              </th></tr></tbody></table></th>
              <th class="small-6 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:350px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
            </tr></tbody></table>
            
            <table style="background:#ffffff;border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><td height="30" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:30px;font-weight:normal;line-height:30px;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table> 

            
            <table style="background:#ffffff;border-collapse:collapse;border-spacing:0;box-sizing:border-box;display:table;padding:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr>
              <th class="small-1 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:50px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
              <th class="small-10 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:500px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
                <h1 style="Margin:0;Margin-bottom:0px;box-sizing:border-box;color:#000000;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Tahoma,sans-serif;font-size:30px;font-weight:700;line-height:1.5em;margin:0;margin-bottom:0px;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;word-wrap:normal">Your account is now active
            </h1>
              </th></tr></tbody></table></th>
              <th class="small-1 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:50px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
            </tr></tbody></table>
            
            <table style="background:#ffffff;border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><td height="25" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:25px;font-weight:normal;line-height:25px;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table> 
            
            <table style="background:#ffffff;border-collapse:collapse;border-spacing:0;box-sizing:border-box;display:table;padding:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr>
                <th class="small-1 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:150px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
                <th class="small-10 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:300px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
                    <center style="box-sizing:border-box;min-width:300px;width:100%">
                        <img src="./Verify/unnamed(1).png" align="center" style="Margin:0 auto;box-sizing:border-box;clear:both;display:block;float:none;margin:0 auto;max-width:100%;outline:none;text-align:center;text-decoration:none;width:auto" class="CToWUd a6T" data-bit="iit" tabindex="0"><div class="a6S" dir="ltr" style="opacity: 0.01; left: 483px; top: 319px;"><div id=":o3" class="T-I J-J5-Ji aQv T-I-ax7 L3 a5q" role="button" tabindex="0" aria-label="Download attachment " jslog="91252; u014N:cOuCgd,Kr2w4b,xr6bB" data-tooltip-class="a1V" data-tooltip="Download"><div class="akn"><div class="aSK J-J5-Ji aYr"></div></div></div></div>
                    </center>
                </th></tr></tbody></table></th>
                <th class="small-1 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:150px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
            </tr></tbody></table>
            
            <table style="background:#ffffff;border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><td height="25" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:25px;font-weight:normal;line-height:25px;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table> 
            
            <table style="background:#ffffff;border-collapse:collapse;border-spacing:0;box-sizing:border-box;display:table;padding:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr>
              <th class="small-1 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:50px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
              <th class="small-10 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:500px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
                <p style="Margin:0;Margin-bottom:0px;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;margin-bottom:0px;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;word-break:normal">
                  Unlock all your account features by verifying your identity.
                </p>
            
                <table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><td height="25" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:25px;font-weight:normal;line-height:25px;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table> 
            
                <center style="box-sizing:border-box;min-width:500px;width:100%">
                  <table class="button" style="Margin:0 0 16px 0;border-collapse:collapse;border-spacing:0;box-sizing:border-box;float:none;margin:0 0 16px 0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:center;vertical-align:top;width:auto"><tbody style="box-sizing:border-box"><tr><td style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><td style="Margin:0;background:#5d45dc;border:none;border-collapse:collapse!important;border-radius:500px;box-sizing:border-box;color:#ffffff;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"><a align="center" href="https://www.kraken.com/pro-mobile-verify" style="border:0 solid #5d45dc;border-radius:69px;box-sizing:border-box;color:#ffffff;display:inline-block;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:700;line-height:1rem;margin-top:4px;min-width:260px;padding:14px 32px 14px 32px;text-align:center;text-decoration:none" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://www.kraken.com/pro-mobile-verify&amp;source=gmail&amp;ust=1675499231525000&amp;usg=AOvVaw0HISRMaC-S3AaVhKK26ByO">
                    Get verified
                  </a></td></tr></tbody></table></td></tr></tbody></table>
                </center>
                <table style="background:#ffffff;border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><td height="10" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:10px;font-weight:normal;line-height:10px;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table> 
            
                <p style="Margin:0;Margin-bottom:0px;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;margin-bottom:0px;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;word-break:normal">
                  Once verified, you'll be able to buy crypto on Kraken, use your preferred payment method and explore our range of assets.
                </p>
            
                <table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><td height="25" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:25px;font-weight:normal;line-height:25px;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table> 
            
                <p style="Margin:0;Margin-bottom:0px;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;margin-bottom:0px;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;word-break:normal">
                  Our verification is automated and usually takes less than 5 minutes to complete.
                </p>
            
              </th></tr></tbody></table></th>
              <th class="small-1 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:50px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
            </tr></tbody></table>
            
            <table style="background:#ffffff;border-collapse:collapse;border-spacing:0;box-sizing:border-box;display:table;padding:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr>
              <th class="small-1 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:50px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"> </th></tr></tbody></table></th>
              <th class="small-10 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:500px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
                <hr style="border:1px solid #cccccc;box-sizing:border-box;margin:30px auto;width:100%">
              </th></tr></tbody></table></th>
              <th class="small-1 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:50px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"> </th></tr></tbody></table></th>
            </tr></tbody></table>
            
            <table style="background:#ffffff;border-collapse:collapse;border-spacing:0;box-sizing:border-box;display:table;padding:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr>
              <th class="small-1 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:50px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
              <th class="small-10 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:500px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
                  <h2 style="Margin:0;Margin-bottom:0px;box-sizing:border-box;color:inherit;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Tahoma,sans-serif;font-size:23px;font-weight:400;line-height:1.5em;margin:0;margin-bottom:0px;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;word-wrap:normal">What's next?</h2>
                    <table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><td height="30" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:30px;font-weight:normal;line-height:30px;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table> 
                <table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;display:table;padding:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr>
                  <th class="small-12 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0!important;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:33.333333%;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
                    <a href="https://www.youtube.com/watch?v=97lh_LjLYD4" style="box-sizing:border-box;color:#5d45dc;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-weight:normal;line-height:1.5em;padding:0;text-align:left;text-decoration:underline" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://www.youtube.com/watch?v%3D97lh_LjLYD4&amp;source=gmail&amp;ust=1675499231525000&amp;usg=AOvVaw1suUseFIsz4uK20-7W3bts">
                      <img src="./Verify/unnamed(2).png" style="border:none;box-sizing:border-box;clear:both;display:block;max-width:100%;outline:none;text-decoration:none;width:auto" class="CToWUd" data-bit="iit">
                    </a>
                  </th></tr></tbody></table></th>
                  <th class="small-4 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
                  </th></tr></tbody></table></th>
                  <th class="small-12 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:8.333333%;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
                    <table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><td height="30" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:30px;font-weight:normal;line-height:30px;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table> 
                  </th></tr></tbody></table></th>
                  <th class="small-12 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0!important;padding-top:0;text-align:left;vertical-align:top;width:58.333333%;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
                    <strong style="box-sizing:border-box">
                    Activate sign-in 2FA before your first transaction
                    </strong>
                    <table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><td height="14" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:14px;font-weight:normal;line-height:14px;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table> 
                    <p style="Margin:0;Margin-bottom:0px;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;margin-bottom:0px;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;word-break:normal">
                    Sign-in 2FA protects your account by asking for a unique code, on top of your password.
                    </p>
                  </th></tr></tbody></table></th>
                </tr></tbody></table>
            
              </th></tr></tbody></table></th>
              <th class="small-1 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:50px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
            </tr></tbody></table>
            
            <table style="background:#ffffff;border-collapse:collapse;border-spacing:0;box-sizing:border-box;display:table;padding:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr>
              <th class="small-1 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:50px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
              <th class="small-10 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:500px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
                <table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><td height="14" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:14px;font-weight:normal;line-height:14px;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table> 
                <p style="Margin:0;Margin-bottom:0px;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;margin-bottom:0px;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;word-break:normal">
                Crypto is exciting and we want you to enjoy it to the fullest.
                Use our <a href="https://support.kraken.com/hc/articles/201396837" style="box-sizing:border-box;color:#5d45dc;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-weight:normal;line-height:1.5em;padding:0;text-align:left;text-decoration:underline" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://support.kraken.com/hc/articles/201396837&amp;source=gmail&amp;ust=1675499231525000&amp;usg=AOvVaw1yPEhVeQy5MvzU-koSMV-I">personal security guides</a> to keep your assets safe.
                </p>
              </th></tr></tbody></table></th>
              <th class="small-1 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:50px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
            </tr></tbody></table>
            

            <table class="rounded-bottom" style="background:#ffffff;border-bottom-left-radius:15px;border-bottom-right-radius:15px;border-collapse:collapse;border-spacing:0;box-sizing:border-box;display:table;padding:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr>
              <th class="small-12 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:600px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
                <table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><td height="30" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:30px;font-weight:normal;line-height:30px;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table> 
              </th>
<th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding:0!important;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:0;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
            </tr></tbody></table>
            
            <table class="collapse" style="background:transparent;border-collapse:collapse;border-spacing:0;box-sizing:border-box;display:table;padding:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr>
              <th class="small-1 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:50px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"> </th></tr></tbody></table></th>
              <th class="small-10 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:500px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
                <table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><td height="30" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:30px;font-weight:normal;line-height:30px;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table> 
            
                <table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><td height="15" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:15px;font-weight:normal;line-height:15px;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table> 
            
                <p style="Margin:0;Margin-bottom:0px;box-sizing:border-box;color:#898989!important;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:14px;font-weight:normal;letter-spacing:0.1px;line-height:1.4;margin:0;margin-bottom:0px;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:center;word-break:normal">© Kraken 2022</p>
            
                <table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><td height="14" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:14px;font-weight:normal;line-height:14px;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table> 
            
                <p style="Margin:0;Margin-bottom:0px;box-sizing:border-box;color:#898989!important;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:14px;font-weight:normal;letter-spacing:0.1px;line-height:1.4;margin:0;margin-bottom:0px;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:center;word-break:normal">Kraken, 237 Kearny St #102, San Francisco, CA 94108, USA</p>
                <p style="Margin:0;Margin-bottom:0px;box-sizing:border-box;color:#898989!important;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:14px;font-weight:normal;letter-spacing:0.1px;line-height:1.4;margin:0;margin-bottom:0px;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:center;word-break:normal"></p>
            
                <table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><td height="14" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:14px;font-weight:normal;line-height:14px;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table> 
            
                <center style="box-sizing:border-box;min-width:500px;width:100%">
                  <table align="center" class="menu" style="Margin:0 auto;border-collapse:collapse;border-spacing:0;box-sizing:border-box;float:none;margin:0 auto;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:center;vertical-align:top;width:auto"><tbody style="box-sizing:border-box"><tr><td style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr>
                    <th style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;float:none;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding:10px;padding-bottom:0;padding-left:0;padding-right:10px;padding-top:0;text-align:center;vertical-align:top;word-break:normal;word-wrap:break-word"><a href="https://facebook.com/KrakenFX" style="box-sizing:border-box;color:#5d45dc;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-weight:normal;line-height:1.5em;padding:0;text-align:left;text-decoration:underline" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://facebook.com/KrakenFX&amp;source=gmail&amp;ust=1675499231525000&amp;usg=AOvVaw2YrGYv9e_xGY73o3cWzt9I">
                      <img class="social-icon CToWUd" src="./Verify/unnamed(3).png" alt="facebook logo" style="border:none;box-sizing:border-box;clear:both;display:block;height:25px;margin:0 10px 0 10px;margin-bottom:1rem;max-width:100%;outline:none;text-decoration:none;width:25px" data-bit="iit">
                    </a></th>
                    <th style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;float:none;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding:10px;padding-bottom:0;padding-left:0;padding-right:10px;padding-top:0;text-align:center;vertical-align:top;word-break:normal;word-wrap:break-word"><a href="https://twitter.com/krakenfx" style="box-sizing:border-box;color:#5d45dc;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-weight:normal;line-height:1.5em;padding:0;text-align:left;text-decoration:underline" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://twitter.com/krakenfx&amp;source=gmail&amp;ust=1675499231525000&amp;usg=AOvVaw0FJVC0S45chvkqROIN2svy">
                      <img class="social-icon social-icon-twitter CToWUd" src="./Verify/unnamed(4).png" alt="twitter logo" style="border:none;box-sizing:border-box;clear:both;display:block;height:20px;margin:0 10px 0 10px;margin-bottom:1rem;margin-top:3px;max-width:100%;outline:none;text-decoration:none;width:24px" data-bit="iit">
                    </a></th>
                    <th style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;float:none;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding:10px;padding-bottom:0;padding-left:0;padding-right:10px;padding-top:0;text-align:center;vertical-align:top;word-break:normal;word-wrap:break-word"><a href="https://www.instagram.com/krakenfx/" style="box-sizing:border-box;color:#5d45dc;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-weight:normal;line-height:1.5em;padding:0;text-align:left;text-decoration:underline" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://www.instagram.com/krakenfx/&amp;source=gmail&amp;ust=1675499231525000&amp;usg=AOvVaw1Eyw719cn9nWGGeVB5UvLn">
                      <img class="social-icon CToWUd" src="./Verify/unnamed(5).png" alt="youtube logo" style="border:none;box-sizing:border-box;clear:both;display:block;height:25px;margin:0 10px 0 10px;margin-bottom:1rem;max-width:100%;outline:none;text-decoration:none;width:25px" data-bit="iit">
                    </a></th>
                    <th style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;float:none;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding:10px;padding-bottom:0;padding-left:0;padding-right:10px;padding-top:0;text-align:center;vertical-align:top;word-break:normal;word-wrap:break-word"><a href="https://linkedin.com/company/krakenfx" style="box-sizing:border-box;color:#5d45dc;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-weight:normal;line-height:1.5em;padding:0;text-align:left;text-decoration:underline" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://linkedin.com/company/krakenfx&amp;source=gmail&amp;ust=1675499231525000&amp;usg=AOvVaw0sH4fAJJd5h5CMDisKibfT">
                      <img class="social-icon CToWUd" src="./Verify/unnamed(6).png" alt="linkedin logo" style="border:none;box-sizing:border-box;clear:both;display:block;height:25px;margin:0 10px 0 10px;margin-bottom:1rem;max-width:100%;outline:none;text-decoration:none;width:25px" data-bit="iit">
                    </a></th>
                    <th style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;float:none;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding:10px;padding-bottom:0;padding-left:0;padding-right:10px;padding-top:0;text-align:center;vertical-align:top;word-break:normal;word-wrap:break-word"><a href="https://www.youtube.com/c/KrakenBitcoinExchange" style="box-sizing:border-box;color:#5d45dc;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-weight:normal;line-height:1.5em;padding:0;text-align:left;text-decoration:underline" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://www.youtube.com/c/KrakenBitcoinExchange&amp;source=gmail&amp;ust=1675499231525000&amp;usg=AOvVaw0wJ_2LUrs5QchMealNw5Ag">
                      <img class="social-icon social-icon-youtube CToWUd" src="./Verify/unnamed(7).png" alt="youtube logo" style="border:none;box-sizing:border-box;clear:both;display:block;height:15px;margin:0 10px 0 10px;margin-bottom:1rem;margin-top:5px;max-width:100%;outline:none;text-decoration:none;width:20px" data-bit="iit">
                    </a></th>
                  </tr></tbody></table></td></tr></tbody></table>
                </center>
            
                <p style="Margin:0;Margin-bottom:0px;box-sizing:border-box;color:rgba(0,0,0,0)!important;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;height:1px;line-height:1.5em;margin:0;margin-bottom:0px;opacity:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;word-break:normal">Anti-Trim: 63a06a141d9ef</p>
              </th></tr></tbody></table></th>
              <th class="small-1 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:50px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;width:100%"><tbody style="box-sizing:border-box"><tr><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:&#39;Celias&#39;,&#39;Roboto&#39;,Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding-bottom:0;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
            </tr></tbody></table>
            
 

</body></html>