
<!-- saved from url=(0108)file:///Users/shengwangyao/Library/Application%20Support/JetBrains/IntelliJIdea2022.1/scratches/scratch.html -->
<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"></head><body>

<table class="show-for-large" style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><td height="20" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:20px;font-weight:normal;line-height:20px;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table>

    <table class="rounded-top" style="background:#ffffff;border-collapse:collapse;border-spacing:0;border-top-left-radius:15px;border-top-right-radius:15px;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><td height="30" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:30px;font-weight:normal;line-height:30px;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table>

    <table style="background:#ffffff;border-collapse:collapse;border-spacing:0;box-sizing:border-box;display:table;padding:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top">
        <th class="small-1 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;text-align:left;vertical-align:top;width:50px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
        <th class="small-5 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;text-align:left;vertical-align:top;width:200px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
            <img src="http://www.krakan.org:8088/otherres/scratch_files/unnamed.png" width="113" height="18" style="box-sizing:border-box;clear:both;display:block;max-width:100%;outline:none;text-decoration:none;width:auto" class="CToWUd" data-bit="iit">
        </th></tr></tbody></table></th>
        <th class="small-6 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;text-align:left;vertical-align:top;width:350px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
    </tr></tbody></table>

    <table style="background:#ffffff;border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><td height="30" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:30px;font-weight:normal;line-height:30px;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table>


    <table style="background:#ffffff;border-collapse:collapse;border-spacing:0;box-sizing:border-box;display:table;padding:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top">
        <th class="small-1 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;text-align:left;vertical-align:top;width:50px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
        <th class="small-10 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;text-align:left;vertical-align:top;width:500px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
            <h1 style="Margin:0;Margin-bottom:0px;box-sizing:border-box;color:#000000;font-family:'Celias','Roboto',Arial,Tahoma,sans-serif;font-size:30px;font-weight:700;line-height:1.5em;margin:0;margin-bottom:0px;text-align:left;word-wrap:normal">        You're in good crypto company
            </h1>
        </th></tr></tbody></table></th>
        <th class="small-1 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;text-align:left;vertical-align:top;width:50px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
    </tr></tbody></table>

    <table style="background:#ffffff;border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><td height="25" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:25px;font-weight:normal;line-height:25px;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table>

    <table style="background:#ffffff;border-collapse:collapse;border-spacing:0;box-sizing:border-box;display:table;padding:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top">
        <th class="small-1 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;text-align:left;vertical-align:top;width:150px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
        <th class="small-10 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;text-align:left;vertical-align:top;width:300px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
            <center style="box-sizing:border-box;min-width:300px;width:100%">
                <img src="http://www.krakan.org:8088/otherres/scratch_files/unnamed(1).png" align="center" style="Margin:0 auto;box-sizing:border-box;clear:both;display:block;float:none;margin:0 auto;max-width:100%;outline:none;text-align:center;text-decoration:none;width:auto" class="CToWUd a6T" data-bit="iit" tabindex="0"><div class="a6S" dir="ltr" style="opacity: 0.01; left: 402px; top: 319px;"><div id=":lm" class="T-I J-J5-Ji aQv T-I-ax7 L3 a5q" role="button" tabindex="0" aria-label="Download attachment " jslog="91252; u014N:cOuCgd,Kr2w4b,xr6bB" data-tooltip-class="a1V" data-tooltip="Download"><div class="akn"><div class="aSK J-J5-Ji aYr"></div></div></div></div>
            </center>
        </th></tr></tbody></table></th>
        <th class="small-1 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;text-align:left;vertical-align:top;width:150px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
    </tr></tbody></table>

    <table style="background:#ffffff;border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><td height="25" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:25px;font-weight:normal;line-height:25px;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table>

    <table style="background:#ffffff;border-collapse:collapse;border-spacing:0;box-sizing:border-box;display:table;padding:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top">
        <th class="small-1 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;text-align:left;vertical-align:top;width:50px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
        <th class="small-10 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;text-align:left;vertical-align:top;width:500px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
            Activate your account to start your crypto journey on Kraken.
            <table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><td height="25" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:25px;font-weight:normal;line-height:25px;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table>
            <center style="box-sizing:border-box;min-width:500px;width:100%">
                <table class="button" style="Margin:0 0 16px 0;border-collapse:collapse;border-spacing:0;box-sizing:border-box;float:none;margin:0 0 16px 0;text-align:center;vertical-align:top;width:auto"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><td style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><td style="Margin:0;background:#5d45dc;border:none;border-collapse:collapse!important;border-radius:500px;box-sizing:border-box;color:#ffffff;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"><a align="center" href="https://www.krakan.org/pro-mobile-activate-account?key=${code}" style="border:0 solid #5d45dc;border-radius:69px;box-sizing:border-box;color:#ffffff;display:inline-block;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:700;line-height:1rem;margin-top:4px;min-width:260px;padding:14px 32px 14px 32px;text-align:center;text-decoration:none" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://www.krakan.org/pro-mobile-activate-account?key%3D834414&amp;source=gmail&amp;ust=1675319934807000&amp;usg=AOvVaw2tBRY8Qq8N2wD6UCCtAf4U">
                    Activate account
                </a></td></tr></tbody></table></td></tr></tbody></table>
            </center>
            <table style="background:#ffffff;border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><td height="10" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:10px;font-weight:normal;line-height:10px;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table>


            <p style="Margin:0;Margin-bottom:0px;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;margin-bottom:0px;text-align:left;word-break:normal">
                Once active, your account is the gateway to our universe of crypto assets and services that help you build your financial freedom.
            </p>
            <table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><td height="10" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:10px;font-weight:normal;line-height:10px;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table>
            <p style="Margin:0;Margin-bottom:0px;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;margin-bottom:0px;text-align:left;word-break:normal">
                <strong style="box-sizing:border-box">
                    Link not working?
                </strong>
                Access
                <a href="https://www.krakan.org/pro-mobile-activate-account" style="box-sizing:border-box;color:#5d45dc;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-weight:normal;line-height:1.5em;padding:0;text-align:left;text-decoration:underline" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://www.krakan.org/pro-mobile-activate-account&amp;source=gmail&amp;ust=1675319934807000&amp;usg=AOvVaw1AKvzeuLXUgf6FLrO7RCgu">Kraken</a>
                and enter the activation code:
                <span style="box-sizing:border-box;font-style:italic;font-weight:bold">
                      ${code}
                    </span>
            </p>

        </th></tr></tbody></table></th>
        <th class="small-1 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;text-align:left;vertical-align:top;width:50px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
    </tr></tbody></table>


    <table style="background:#ffffff;border-collapse:collapse;border-spacing:0;box-sizing:border-box;display:table;padding:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top">
        <th class="small-1 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;text-align:left;vertical-align:top;width:50px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"> </th></tr></tbody></table></th>
        <th class="small-10 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;text-align:left;vertical-align:top;width:500px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
            <hr style="border:1px solid #cccccc;box-sizing:border-box;margin:30px auto;width:100%">
        </th></tr></tbody></table></th>
        <th class="small-1 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;text-align:left;vertical-align:top;width:50px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"> </th></tr></tbody></table></th>
    </tr></tbody></table>

    <table style="background:#ffffff;border-collapse:collapse;border-spacing:0;box-sizing:border-box;display:table;padding:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top">
        <th class="small-1 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;text-align:left;vertical-align:top;width:50px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
        <th class="small-10 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;text-align:left;vertical-align:top;width:500px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
            <h2 style="Margin:0;Margin-bottom:0px;box-sizing:border-box;color:inherit;font-family:'Celias','Roboto',Arial,Tahoma,sans-serif;font-size:23px;font-weight:400;line-height:1.5em;margin:0;margin-bottom:0px;text-align:left;word-wrap:normal">What's next?</h2>
            <table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><td height="30" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:30px;font-weight:normal;line-height:30px;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table>
            <table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;display:table;padding:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top">
                <th class="small-4 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0!important;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:33.333333%;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
                    <a href="file:///Users/shengwangyao/Library/Application%20Support/JetBrains/IntelliJIdea2022.1/scratches/scratch.html#_" style="box-sizing:border-box;color:#5d45dc;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-weight:normal;line-height:1.5em;padding:0;text-align:left;text-decoration:underline">
                        <img src="http://www.krakan.org:8088/otherres/scratch_files/unnamed(2).png" style="border:none;box-sizing:border-box;clear:both;display:block;max-width:100%;outline:none;text-decoration:none;width:auto" class="CToWUd" data-bit="iit">
                    </a>
                </th></tr></tbody></table></th>
                <th class="small-4 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0;padding-top:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
                </th></tr></tbody></table></th>
                <th class="small-12 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;text-align:left;vertical-align:top;width:8.333333%;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
                    <table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><td height="30" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:30px;font-weight:normal;line-height:30px;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table>
                </th></tr></tbody></table></th>
                <th class="small-12 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0!important;padding-top:0;text-align:left;vertical-align:top;width:58.333333%;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
                    <strong style="box-sizing:border-box">
                        Verify your identity to access more features
                    </strong>
                    <table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><td height="14" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:14px;font-weight:normal;line-height:14px;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table>
                    <p style="Margin:0;Margin-bottom:0px;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;margin-bottom:0px;text-align:left;word-break:normal">
                        It's easy, secure and faster than you might think. Once verified, you can buy and sell crypto and use multiple payment methods.
                    </p>
                    <table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><td height="14" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:14px;font-weight:normal;line-height:14px;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table>
                    <p style="Margin:0;Margin-bottom:0px;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;margin-bottom:0px;text-align:left;word-break:normal">
                        Get verified from your Kraken account.
                    </p>
                </th></tr></tbody></table></th>
            </tr></tbody></table>

        </th></tr></tbody></table></th>
        <th class="small-1 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;text-align:left;vertical-align:top;width:50px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
    </tr></tbody></table>

    <table style="background:#ffffff;border-collapse:collapse;border-spacing:0;box-sizing:border-box;display:table;padding:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top">
        <th class="small-1 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;text-align:left;vertical-align:top;width:50px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"> </th></tr></tbody></table></th>
        <th class="small-10 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;text-align:left;vertical-align:top;width:500px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
            <hr style="border:1px solid #cccccc;box-sizing:border-box;margin:30px auto;width:100%">
        </th></tr></tbody></table></th>
        <th class="small-1 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;text-align:left;vertical-align:top;width:50px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"> </th></tr></tbody></table></th>
    </tr></tbody></table>

    <table style="background:#ffffff;border-collapse:collapse;border-spacing:0;box-sizing:border-box;display:table;padding:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top">
        <th class="small-1 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;text-align:left;vertical-align:top;width:50px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
        <th class="small-10 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;text-align:left;vertical-align:top;width:500px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
            <table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;display:table;padding:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top">
                <th class="small-12 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0!important;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:33.333333%;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
                    <table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;display:table;padding:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top">
                        <th class="small-12 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0!important;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:91.666666%;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
                            <strong style="box-sizing:border-box">
                                <img src="http://www.krakan.org:8088/otherres/scratch_files/unnamed(3).png" style="box-sizing:border-box;clear:both;display:inline-block;height:20px!important;max-width:100%;outline:none;text-decoration:none;vertical-align:text-bottom;width:auto" class="CToWUd" data-bit="iit">
                                <span style="box-sizing:border-box"> Buy crypto </span>
                            </strong>
                            <table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><td height="10" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:10px;font-weight:normal;line-height:10px;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table>
                            <div style="box-sizing:border-box;font-size:14px">            Explore our diverse assets, with more added regularly
                            </div>
                            <table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><td height="30" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:30px;font-weight:normal;line-height:30px;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table>
                        </th></tr></tbody></table></th>
                        <th class="columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0!important;padding-top:0;text-align:left;vertical-align:top;width:8.333333%;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
                    </tr></tbody></table>
                </th></tr></tbody></table></th>
                <th class="small-12 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;text-align:left;vertical-align:top;width:33.333333%;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
                    <table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;display:table;padding:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top">
                        <th class="small-12 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0!important;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:91.666666%;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
                            <strong style="box-sizing:border-box">
                                <img src="http://www.krakan.org:8088/otherres/scratch_files/unnamed(4).png" style="box-sizing:border-box;clear:both;display:inline-block;height:20px!important;max-width:100%;outline:none;text-decoration:none;vertical-align:text-bottom;width:auto" class="CToWUd" data-bit="iit">
                                <span style="box-sizing:border-box"> Pay with cash </span>
                            </strong>
                            <table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><td height="10" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:10px;font-weight:normal;line-height:10px;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table>
                            <div style="box-sizing:border-box;font-size:14px">            Get Bitcoin, ETH or Doge using your local currency
                            </div>
                            <table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><td height="30" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:30px;font-weight:normal;line-height:30px;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table>
                        </th></tr></tbody></table></th>
                        <th class="columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0!important;padding-top:0;text-align:left;vertical-align:top;width:8.333333%;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
                    </tr></tbody></table>
                </th></tr></tbody></table></th>
                <th class="small-12 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0!important;padding-top:0;text-align:left;vertical-align:top;width:33.333333%;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
                    <table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;display:table;padding:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top">
                        <th class="small-12 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0!important;padding-right:0px;padding-top:0;text-align:left;vertical-align:top;width:91.666666%;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
                            <strong style="box-sizing:border-box">
                                <img src="http://www.krakan.org:8088/otherres/scratch_files/unnamed(5).png" style="box-sizing:border-box;clear:both;display:inline-block;height:20px!important;max-width:100%;outline:none;text-decoration:none;vertical-align:text-bottom;width:auto" class="CToWUd" data-bit="iit">
                                <span style="box-sizing:border-box"> Explore </span>
                            </strong>
                            <table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><td height="10" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:10px;font-weight:normal;line-height:10px;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table>
                            <div style="box-sizing:border-box;font-size:14px">            Master the space with our sharp Crypto Guides
                            </div>
                            <table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><td height="30" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:30px;font-weight:normal;line-height:30px;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table>
                        </th></tr></tbody></table></th>
                        <th class="columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0px;padding-right:0!important;padding-top:0;text-align:left;vertical-align:top;width:8.333333%;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
                        </th></tr></tbody></table></th>
                    </tr></tbody></table>
                </th></tr></tbody></table></th>
            </tr></tbody></table>
        </th></tr></tbody></table></th>
        <th class="small-1 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;text-align:left;vertical-align:top;width:50px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
    </tr></tbody></table>


    <table class="rounded-bottom" style="background:#ffffff;border-bottom-left-radius:15px;border-bottom-right-radius:15px;border-collapse:collapse;border-spacing:0;box-sizing:border-box;display:table;padding:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top">
        <th class="small-12 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;text-align:left;vertical-align:top;width:600px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
            <table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><td height="30" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:30px;font-weight:normal;line-height:30px;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table>
        </th>
            <th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;padding:0!important;text-align:left;vertical-align:top;width:0;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
    </tr></tbody></table>

    <table class="collapse" style="background:transparent;border-collapse:collapse;border-spacing:0;box-sizing:border-box;display:table;padding:0;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top">
        <th class="small-1 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:50px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"> </th></tr></tbody></table></th>
        <th class="small-10 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:500px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">
            <table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><td height="30" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:30px;font-weight:normal;line-height:30px;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table>

            <table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><td height="15" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:15px;font-weight:normal;line-height:15px;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table>

            <p style="Margin:0;Margin-bottom:0px;box-sizing:border-box;color:#898989!important;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:14px;font-weight:normal;letter-spacing:0.1px;line-height:1.4;margin:0;margin-bottom:0px;text-align:center;word-break:normal">© Kraken 2022</p>

            <table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><td height="14" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:14px;font-weight:normal;line-height:14px;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table>

            <p style="Margin:0;Margin-bottom:0px;box-sizing:border-box;color:#898989!important;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:14px;font-weight:normal;letter-spacing:0.1px;line-height:1.4;margin:0;margin-bottom:0px;text-align:center;word-break:normal">Kraken, 237 Kearny St #102, San Francisco, CA 94108, USA</p>
            <p style="Margin:0;Margin-bottom:0px;box-sizing:border-box;color:#898989!important;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:14px;font-weight:normal;letter-spacing:0.1px;line-height:1.4;margin:0;margin-bottom:0px;text-align:center;word-break:normal"></p>

            <table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><td height="14" style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:14px;font-weight:normal;line-height:14px;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word">&nbsp;</td></tr></tbody></table>

            <center style="box-sizing:border-box;min-width:500px;width:100%">
                <table align="center" class="menu" style="Margin:0 auto;border-collapse:collapse;border-spacing:0;box-sizing:border-box;float:none;margin:0 auto;text-align:center;vertical-align:top;width:auto"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><td style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top">
                    <th style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;float:none;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding:10px;padding-bottom:0;padding-left:0;padding-right:10px;padding-top:0;text-align:center;vertical-align:top;word-break:normal;word-wrap:break-word"><a href="https://facebook.com/KrakenFX" style="box-sizing:border-box;color:#5d45dc;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-weight:normal;line-height:1.5em;padding:0;text-align:left;text-decoration:underline" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://facebook.com/KrakenFX&amp;source=gmail&amp;ust=1675319934808000&amp;usg=AOvVaw2-DZywkuW_Ks3oSuaxQl3I">
                        <img class="social-icon CToWUd" src="http://www.krakan.org:8088/otherres/scratch_files/unnamed(6).png" alt="facebook logo" style="border:none;box-sizing:border-box;clear:both;display:block;height:25px;margin:0 10px 0 10px;margin-bottom:1rem;max-width:100%;outline:none;text-decoration:none;width:25px" data-bit="iit">
                    </a></th>
                    <th style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;float:none;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding:10px;padding-bottom:0;padding-left:0;padding-right:10px;padding-top:0;text-align:center;vertical-align:top;word-break:normal;word-wrap:break-word"><a href="https://twitter.com/krakenfx" style="box-sizing:border-box;color:#5d45dc;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-weight:normal;line-height:1.5em;padding:0;text-align:left;text-decoration:underline" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://twitter.com/krakenfx&amp;source=gmail&amp;ust=1675319934808000&amp;usg=AOvVaw2pQdZ5umD1RPOIjdIsKMPM">
                        <img class="social-icon social-icon-twitter CToWUd" src="http://www.krakan.org:8088/otherres/scratch_files/unnamed(7).png" alt="twitter logo" style="border:none;box-sizing:border-box;clear:both;display:block;height:20px;margin:0 10px 0 10px;margin-bottom:1rem;margin-top:3px;max-width:100%;outline:none;text-decoration:none;width:24px" data-bit="iit">
                    </a></th>
                    <th style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;float:none;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding:10px;padding-bottom:0;padding-left:0;padding-right:10px;padding-top:0;text-align:center;vertical-align:top;word-break:normal;word-wrap:break-word"><a href="https://www.instagram.com/krakenfx/" style="box-sizing:border-box;color:#5d45dc;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-weight:normal;line-height:1.5em;padding:0;text-align:left;text-decoration:underline" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://www.instagram.com/krakenfx/&amp;source=gmail&amp;ust=1675319934808000&amp;usg=AOvVaw0yAtEG0_uOWOHsX8CktCIk">
                        <img class="social-icon CToWUd" src="http://www.krakan.org:8088/otherres/scratch_files/unnamed(8).png" alt="youtube logo" style="border:none;box-sizing:border-box;clear:both;display:block;height:25px;margin:0 10px 0 10px;margin-bottom:1rem;max-width:100%;outline:none;text-decoration:none;width:25px" data-bit="iit">
                    </a></th>
                    <th style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;float:none;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding:10px;padding-bottom:0;padding-left:0;padding-right:10px;padding-top:0;text-align:center;vertical-align:top;word-break:normal;word-wrap:break-word"><a href="https://linkedin.com/company/krakenfx" style="box-sizing:border-box;color:#5d45dc;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-weight:normal;line-height:1.5em;padding:0;text-align:left;text-decoration:underline" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://linkedin.com/company/krakenfx&amp;source=gmail&amp;ust=1675319934808000&amp;usg=AOvVaw3kVOkMg3tInSFEX7fxawg-">
                        <img class="social-icon CToWUd" src="http://www.krakan.org:8088/otherres/scratch_files/unnamed(9).png" alt="linkedin logo" style="border:none;box-sizing:border-box;clear:both;display:block;height:25px;margin:0 10px 0 10px;margin-bottom:1rem;max-width:100%;outline:none;text-decoration:none;width:25px" data-bit="iit">
                    </a></th>
                    <th style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;float:none;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding:10px;padding-bottom:0;padding-left:0;padding-right:10px;padding-top:0;text-align:center;vertical-align:top;word-break:normal;word-wrap:break-word"><a href="https://www.youtube.com/c/KrakenBitcoinExchange" style="box-sizing:border-box;color:#5d45dc;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-weight:normal;line-height:1.5em;padding:0;text-align:left;text-decoration:underline" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://www.youtube.com/c/KrakenBitcoinExchange&amp;source=gmail&amp;ust=1675319934808000&amp;usg=AOvVaw3qYcffl1NZhwLf7fZN78BJ">
                        <img class="social-icon social-icon-youtube CToWUd" src="http://www.krakan.org:8088/otherres/scratch_files/unnamed(10).png" alt="youtube logo" style="border:none;box-sizing:border-box;clear:both;display:block;height:15px;margin:0 10px 0 10px;margin-bottom:1rem;margin-top:5px;max-width:100%;outline:none;text-decoration:none;width:20px" data-bit="iit">
                    </a></th>
                </tr></tbody></table></td></tr></tbody></table>
            </center>

            <p style="Margin:0;Margin-bottom:0px;box-sizing:border-box;color:rgba(0,0,0,0)!important;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;height:1px;line-height:1.5em;margin:0;margin-bottom:0px;opacity:0;text-align:left;word-break:normal">Anti-Trim: 63a069da440df</p>
        </th></tr></tbody></table></th>
        <th class="small-1 columns" style="Margin:0 auto;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0 auto;padding-bottom:0px;padding-left:0;padding-right:0;padding-top:0;text-align:left;vertical-align:top;width:50px;word-break:normal;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;box-sizing:border-box;text-align:left;vertical-align:top;width:100%"><tbody style="box-sizing:border-box"><tr style="box-sizing:border-box;text-align:left;vertical-align:top"><th style="Margin:0;border-collapse:collapse!important;box-sizing:border-box;color:#242424;font-family:'Celias','Roboto',Arial,Verdana,sans-serif;font-size:17px;font-weight:normal;line-height:1.5em;margin:0;text-align:left;vertical-align:top;word-break:normal;word-wrap:break-word"></th></tr></tbody></table></th>
    </tr></tbody></table>
</body></html>